fedora_bot: support cockpit-composer
osbuild/fedora-bot pull request #15
Opened 2022-02-16 12:52 UTC by jkozol

2022-02-16 22:39 UTC, ochosi commented
Looks good - thanks!
I guess as soon as you're ready in cockpit-composer to switch to our automation (i.e. set up packit, drop the Makefile and let the specfile contain all the generated changes like the release version) we can go ahead merge this.

That said, fedora-bot is non-destructive, all it does is scheduling builds for latest Fedora dist-git versions so in theory it could be merged anytime.

2022-02-16 22:39 UTC, ochosi requested changes

2022-02-16 22:39 UTC, ochosi commented on fedora_bot.py
> +              "cockpit-composer":  "https://koji.fedoraproject.org/koji/packageinfo?packageID=28261" }
```suggestion
              "cockpit-composer": "https://koji.fedoraproject.org/koji/packageinfo?packageID=28261" }
```

2022-02-16 22:39 UTC, ochosi commented on fedora_bot.py
> +    components = ['osbuild','osbuild-composer','koji-osbuild', 'cockpit-composer']
```suggestion
    components = ['osbuild','osbuild-composer','koji-osbuild','cockpit-composer']
```

2022-02-17 10:27 UTC, jkozol commented
Will fix these whitespace issues. 

Also, I am going to temporarily leave this as a draft until I talk more with cockpit. I discussed this briefly with @kkoukiou and she recommended that we continue to use cockpit's release tools just as their other plugins do.

2022-07-25 12:05 UTC, closed without merging